name: dojo-env-ts-mvp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.10
  - jupyter=1.0.0
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pandas=1.5.3
  - statsmodels=0.13.5
  - pmdarima=2.0.3
  - pandas-datareader=0.10.0
  - numpy=1.23.4
  - conda-forge::shap=0.41.0
  - seaborn=0.12.2
  - scipy==1.10.1
  - pymysql==1.0.3
  - sqlalchemy==2.0.9
  - sqlalchemy-utils
  - beautifulsoup4=4.12.2
  - conda-forge::tabulate
  - conda-forge::xlsxwriter
  # - conda-forge::dataframe_image
  - nltk=3.8.1
  - wordcloud=1.8.2.2
  - gensim=4.3.1
  # - conda-forge::spacy
  - conda-forge::lime=0.2.0.1
  - conda-forge::imbalanced-learn=0.10.1



